development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

# This file is replace by Heroku on deploy. The settings below are just for reference.
production:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
